[package]
name = "client"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "sdb"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
argh = "0.1"
rustyline = "15.0"
tracing = "0.1"
tracing-subscriber = "0.3"

sdb = { path = "../sdb" }
