[package]
name = "sdb"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { version = "0.29", default-features = false, features = [
    "process",
    "ptrace",
    "signal",
] }
num-traits = "0.2"
num-derive = "0.4"
procfs = "0.17"
thiserror = "1.0"
tracing = "0.1"
